
const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
const API_IMAGE_BASE_URL = process.env.REACT_APP_API_BASE_IMAGE_URL;
const ACCESS_TOKEN_AUTH = process.env.REACT_APP_API_ACCESS_TOKEN;

export{
	API_BASE_URL,
	API_IMAGE_BASE_URL,
	ACCESS_TOKEN_AUTH
}
